### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [EverydayBitcoiner/multisig-backup#1]
Not sure if I'm doing this wrong...

```sh
(venv) micah@io multisig-backup % python3 create_backup_cards.py
Enter wallet name (leave blank to use default -> 'Multisig Backup'): 
Paste the 2/3 multisig wallet descriptor from Sparrow Wallet: wsh(sortedmulti(2,Keystore1,Keystore2,Keystore3))
Entire desired qr code density as an integer ('21'=S-21x21, '25'=M-25x25, '29'=L-29x29). Leave blank to use default (M): 
Traceback (most recent call last):
  File "/Users/micah/Downloads/multisig-backup/create_backup_cards.py", line 189, in <module>
    xpub1 = key_info_1.split(']')[1].split('/')[0]
IndexError: list index out of range
```

**Comment by EverydayBitcoiner** [comment]
Ah, should have been more clear in the instructions. You'll want to past in the full descriptor. You can get it by clicking the edit button in Sparrow (far right in attached image).

![image](https://user-images.githubusercontent.com/119913286/207152994-90c20359-7799-4b4b-a058-25afd21f04db.png)

**Comment by EverydayBitcoiner** [comment]
Then just copy and paste the descriptor from the box.
![image](https://user-images.githubusercontent.com/119913286/207153102-7dc6cfde-afc0-4e36-b8a1-dcf3caf5b4e4.png)

**Comment by EverydayBitcoiner** [comment]
Added clarifying instructions to README to clarify how to get the full wallet descriptor from sparrow.
